version: '3.8'

volumes:
  n8n_data:

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-simple
    restart: unless-stopped
    ports:
      - '5678:5678'
    environment:
      # n8n Configuration
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production

      # Security
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123

      # 기타 설정
      - GENERIC_TIMEZONE=Asia/Seoul
      - N8N_DEFAULT_LOCALE=ko

    volumes:
      - n8n_data:/home/node/.n8n
